version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - LISTEN_PORT:LISTEN_PORT/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
